<a href="https://colab.research.google.com/github/gotjd709/AI_class_KSA/blob/main/20_12_14_Mon_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import tensorflow as tf
# input data(mini batch)
# t = 0
X0_batch = np.array([[0, 1, 2],
 [3, 4, 5],
 [6, 7, 8],
 [9, 0, 1]], dtype=np.float32)
# t = 1
X1_batch = np.array([[9, 8, 7],
 [3, 4, 5],
 [6, 5, 4],
 [3, 2, 1]], dtype=np.float32)
print(f"X0_batch = {X0_batch.shape}")
print(f"X1_batch = {X1_batch.shape}")

X0_batch = (4, 3)
X1_batch = (4, 3)


In [4]:
# input data(mini batch)
...
hidden_size = 2
Wx = tf.Variable(tf.random.normal([3, hidden_size], dtype=tf.float32))
Wy = tf.Variable(tf.random.normal([hidden_size, hidden_size], dtype=tf.float32))
b = tf.Variable(tf.zeros([1, hidden_size], dtype=tf.float32))
@tf.function
def run(X0, X1):
 Y0 = tf.tanh(tf.matmul(X0, Wx) + b)
 Y1 = tf.tanh(tf.matmul(Y0, Wy) + tf.matmul(X1, Wx) + b)
 return Y0, Y1
_Y0, _Y1 = run(X0_batch, X1_batch)
print(f"Y0:{_Y0.shape}\n{_Y0}")
print(f"Y1:{_Y1.shape}\n{_Y1}")


Y0:(4, 2)
[[ 0.04094705  0.18347883]
 [-0.98887855  0.9632678 ]
 [-0.9999423   0.99898565]
 [-0.999996    1.        ]]
Y1:(4, 2)
[[-0.9999997   0.99993724]
 [-0.95863134  0.99704844]
 [-0.9998039   0.99983674]
 [-0.96256304  0.99399865]]


In [7]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers
# one hot encoding
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]
sequence_length = 1
x_data = np.array([[h]], dtype=np.float32)
hidden_size = 2
cell = layers.SimpleRNNCell(units=hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)
print(f"x_data = {x_data.shape}\n{x_data}")
print(f"outputs = {outputs.shape}\n{outputs}")
print(f"states = {states.shape}\n{states}")

x_data = (1, 1, 4)
[[[1. 0. 0. 0.]]]
outputs = (1, 1, 2)
[[[ 0.5513723 -0.6466778]]]
states = (1, 2)
[[ 0.5513723 -0.6466778]]


In [9]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers
# one hot encoding
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]
sequence_length = 5
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)
hidden_size = 2
cell = layers.SimpleRNNCell(units=hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)
print(f"x_data = {x_data.shape}\n{x_data}")
print(f"outputs = {outputs.shape}\n{outputs}")
print(f"states = {states.shape}\n{states}")

x_data = (1, 5, 4)
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]]
outputs = (1, 5, 2)
[[[-0.67581016 -0.64976335]
  [ 0.2855474   0.6735734 ]
  [-0.5084464   0.11793243]
  [-0.41600007  0.79334867]
  [-0.66501933  0.67582077]]]
states = (1, 2)
[[-0.66501933  0.67582077]]


In [11]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers
# one hot encoding
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]
sequence_length = 5
x_data = np.array([[h, e, l, l, o],
 [e, l, l, o, h],
 [l, l, o, h, e]], dtype=np.float32)
hidden_size = 2
cell = layers.SimpleRNNCell(units=hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)
print(f"x_data = {x_data.shape}\n{x_data}")
print(f"outputs = {outputs.shape}\n{outputs}")
print(f"states = {states.shape}\n{states}")


x_data = (3, 5, 4)
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]]]
outputs = (3, 5, 2)
[[[ 0.3149435   0.65069366]
  [ 0.18671021 -0.19031303]
  [-0.826411    0.20033167]
  [-0.1378366   0.47910368]
  [ 0.5618133  -0.05594476]]

 [[ 0.03455598  0.47272328]
  [-0.56994075 -0.22059636]
  [-0.5373646   0.6007741 ]
  [ 0.77181756  0.09487037]
  [-0.21867627  0.22134   ]]

 [[-0.72224206  0.16719662]
  [-0.23653603  0.44905716]
  [ 0.60088164  0.02859289]
  [-0.12809323  0.36512488]
  [ 0.34598085  0.29643008]]]
states = (3, 2)
[[ 0.5618133  -0.05594476]
 [-0.21867627  0.22134   ]
 [ 0.34598085  0.29643008]]


In [12]:
import numpy as np
import tensorflow as tf
model = tf.keras.Sequential()
# 64개의 유닛을 가진 완전 연결 층을 모델에 추가
model.add(tf.keras.layers.Dense(64, activation='relu'))
# 또 하나를 추가
model.add(tf.keras.layers.Dense(64, activation='relu'))
# 10개의 출력 유닛을 가진 소프트맥스 층을 추가
model.add(tf.keras.layers.Dense(10, activation='softmax'))

In [13]:
import numpy as np
import tensorflow as tf
model = tf.keras.Sequential([
 tf.keras.layers.Dense(64, activation='relu', input_shape=(32,)),
 tf.keras.layers.Dense(64, activation='relu'),
 tf.keras.layers.Dense(10, activation='softmax')
])
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
 loss='categorical_crossentropy',
 metrics=['accuracy'])

In [15]:
# many to one 

import numpy as np
import tensorflow as tf
# data
xa = [[1],[2],[3]]; ya = [4]
xb = [[2],[3],[4]]; yb = [5]
xc = [[3],[4],[5]]; yc = [6]
x = np.array([xa, xb, xc])
y = np.array([ya, yb, yc])
print(f"x.shape = {x.shape}")
print(f"y.shape = {y.shape}")
# make a model
model = tf.keras.Sequential([
 tf.keras.Input(shape=(3,1), name='input'),
 tf.keras.layers.SimpleRNN(100, name='RNN'),
 tf.keras.layers.Dense(1, name='output')
])
model.summary()
# compile
model.compile(loss='mse', optimizer='adam')
# run model
model.fit(x, y, epochs=100, batch_size=1, verbose=0)
# test model
print(f"1, 2, 3 next? {model.predict([[[1],[2],[3]]])}")
print(f"2, 3, 4 next? {model.predict([[[2],[3],[4]]])}")
print(f"3, 4, 5 next? {model.predict([[[3],[4],[5]]])}")


x.shape = (3, 3, 1)
y.shape = (3, 1)
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
RNN (SimpleRNN)              (None, 100)               10200     
_________________________________________________________________
output (Dense)               (None, 1)                 101       
Total params: 10,301
Trainable params: 10,301
Non-trainable params: 0
_________________________________________________________________
1, 2, 3 next? [[3.910697]]
2, 3, 4 next? [[5.156431]]
3, 4, 5 next? [[5.882587]]


In [16]:
# Functional API version

import numpy as np
import tensorflow as tf
# data
xa = [[1],[2],[3]]; ya = [4]
xb = [[2],[3],[4]]; yb = [5]
xc = [[3],[4],[5]]; yc = [6]
x = np.array([xa, xb, xc])
y = np.array([ya, yb, yc])
print(f"x.shape = {x.shape}")
print(f"y.shape = {y.shape}")
# make a model
input_layer = tf.keras.Input(shape=(3,1), name='input')
rnn_layer = tf.keras.layers.SimpleRNN(100, name='RNN')(input_layer)
output_layer = tf.keras.layers.Dense(1, name='output')(rnn_layer)
model = tf.keras.Model(input_layer, output_layer)
model.summary()
# compile
model.compile(loss='mse', optimizer='adam')
# run model
model.fit(x, y, epochs=100, batch_size=1, verbose=0)
# test model
print(f"1, 2, 3 next? {model.predict([[[1],[2],[3]]])}")
print(f"2, 3, 4 next? {model.predict([[[2],[3],[4]]])}")
print(f"3, 4, 5 next? {model.predict([[[3],[4],[5]]])}")

x.shape = (3, 3, 1)
y.shape = (3, 1)
Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (InputLayer)           [(None, 3, 1)]            0         
_________________________________________________________________
RNN (SimpleRNN)              (None, 100)               10200     
_________________________________________________________________
output (Dense)               (None, 1)                 101       
Total params: 10,301
Trainable params: 10,301
Non-trainable params: 0
_________________________________________________________________
1, 2, 3 next? [[3.930095]]
2, 3, 4 next? [[5.1972966]]
3, 4, 5 next? [[5.911331]]


In [17]:
# Stacked many to one

import numpy as np
import tensorflow as tf
# data
xa = [[1],[2],[3]]; ya = [4]
xb = [[2],[3],[4]]; yb = [5]
xc = [[3],[4],[5]]; yc = [6]
x = np.array([xa, xb, xc])
y = np.array([ya, yb, yc])
print(f"x.shape = {x.shape}")
print(f"y.shape = {y.shape}")
# make a model
input_layer = tf.keras.Input(shape=(3,1), name='input')
rnn_layer0 = tf.keras.layers.SimpleRNN(100, return_sequences=True, name='RNN0')(input_layer)
rnn_layer1 = tf.keras.layers.SimpleRNN(100, name='RNN1')(rnn_layer0)
output_layer = tf.keras.layers.Dense(1, name='output')(rnn_layer1)
model = tf.keras.Model(input_layer, output_layer)
model.summary()
# compile
model.compile(loss='mse', optimizer='adam')
# run model
model.fit(x, y, epochs=100, batch_size=1, verbose=0)
# test model
print(f"1, 2, 3 next? {model.predict([[[1],[2],[3]]])}")
print(f"2, 3, 4 next? {model.predict([[[2],[3],[4]]])}")
print(f"3, 4, 5 next? {model.predict([[[3],[4],[5]]])}")


x.shape = (3, 3, 1)
y.shape = (3, 1)
Model: "functional_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (InputLayer)           [(None, 3, 1)]            0         
_________________________________________________________________
RNN0 (SimpleRNN)             (None, 3, 100)            10200     
_________________________________________________________________
RNN1 (SimpleRNN)             (None, 100)               20100     
_________________________________________________________________
output (Dense)               (None, 1)                 101       
Total params: 30,401
Trainable params: 30,401
Non-trainable params: 0
_________________________________________________________________
1, 2, 3 next? [[3.917168]]
2, 3, 4 next? [[5.091848]]
3, 4, 5 next? [[5.8974648]]


In [18]:
# many to many

import numpy as np
import tensorflow as tf
# data
xa = [[1],[2],[3]]; ya = [[2],[3],[4]]
xb = [[2],[3],[4]]; yb = [[3],[4],[5]]
xc = [[3],[4],[5]]; yc = [[4],[5],[6]]
x = np.array([xa, xb, xc])
y = np.array([ya, yb, yc])
print(f"x.shape = {x.shape}")
print(f"y.shape = {y.shape}")
# make a model
model = tf.keras.Sequential([
 tf.keras.Input(shape=(3,1), name='input'),
 tf.keras.layers.SimpleRNN(100, return_sequences=True, name='RNN'),
 tf.keras.layers.Dense(1, name='output')
])
model.summary()
# compile
model.compile(loss='mse', optimizer='adam')
# run model
model.fit(x, y, epochs=100, batch_size=1, verbose=0)
# test model
print(f"1, 2, 3 next? {model.predict([[[1],[2],[3]]])}")
print(f"2, 3, 4 next? {model.predict([[[2],[3],[4]]])}")
print(f"3, 4, 5 next? {model.predict([[[3],[4],[5]]])}")

x.shape = (3, 3, 1)
y.shape = (3, 3, 1)
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
RNN (SimpleRNN)              (None, 3, 100)            10200     
_________________________________________________________________
output (Dense)               (None, 3, 1)              101       
Total params: 10,301
Trainable params: 10,301
Non-trainable params: 0
_________________________________________________________________
1, 2, 3 next? [[[2.079409 ]
  [2.989925 ]
  [3.9544044]]]
2, 3, 4 next? [[[3.06693 ]
  [4.120216]
  [5.092584]]]
3, 4, 5 next? [[[3.8413677]
  [4.915263 ]
  [5.949472 ]]]


In [19]:
# Functional API

import numpy as np
import tensorflow as tf
# data
xa = [[1],[2],[3]]; ya = [[2],[3],[4]]
xb = [[2],[3],[4]]; yb = [[3],[4],[5]]
xc = [[3],[4],[5]]; yc = [[4],[5],[6]]
x = np.array([xa, xb, xc])
y = np.array([ya, yb, yc])
print(f"x.shape = {x.shape}")
print(f"y.shape = {y.shape}")
# make a model
input_layer = tf.keras.Input(shape=(3,1), name='input')
rnn_layer = tf.keras.layers.SimpleRNN(100, return_sequences=True, name='RNN')(input_layer)
# 모든 time slice에 Dense layer를 적용
output_layer = tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(1), name='output')(rnn_layer)
model = tf.keras.Model(input_layer, output_layer)
model.summary()
# compile
model.compile(loss='mse', optimizer='adam')
# run model
model.fit(x, y, epochs=100, batch_size=1, verbose=0)
# test model
print(f"1, 2, 3 next? {model.predict([[[1],[2],[3]]])}")
print(f"2, 3, 4 next? {model.predict([[[2],[3],[4]]])}")
print(f"3, 4, 5 next? {model.predict([[[3],[4],[5]]])}")

x.shape = (3, 3, 1)
y.shape = (3, 3, 1)
Model: "functional_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (InputLayer)           [(None, 3, 1)]            0         
_________________________________________________________________
RNN (SimpleRNN)              (None, 3, 100)            10200     
_________________________________________________________________
output (TimeDistributed)     (None, 3, 1)              101       
Total params: 10,301
Trainable params: 10,301
Non-trainable params: 0
_________________________________________________________________
1, 2, 3 next? [[[2.0127742]
  [2.9899442]
  [3.969791 ]]]
2, 3, 4 next? [[[3.0689538]
  [4.1165495]
  [5.0805283]]]
3, 4, 5 next? [[[3.939261 ]
  [4.9191546]
  [5.959715 ]]]


In [20]:
# Stacked many to many

import numpy as np
import tensorflow as tf
# data
xa = [[1],[2],[3]]; ya = [[2],[3],[4]]
xb = [[2],[3],[4]]; yb = [[3],[4],[5]]
xc = [[3],[4],[5]]; yc = [[4],[5],[6]]
x = np.array([xa, xb, xc])
y = np.array([ya, yb, yc])
print(f"x.shape = {x.shape}")
print(f"y.shape = {y.shape}")
# make a model
input_layer = tf.keras.Input(shape=(3,1), name='input')
rnn_layer0 = tf.keras.layers.SimpleRNN(100, return_sequences=True, name='RNN0')(input_layer)
rnn_layer1 = tf.keras.layers.SimpleRNN(100, return_sequences=True, name='RNN1')(rnn_layer0)
output_layer = tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(1), name='output')(rnn_layer1)
model = tf.keras.Model(input_layer, output_layer)
model.summary()
# compile
model.compile(loss='mse', optimizer='adam')
# run model
model.fit(x, y, epochs=100, batch_size=1, verbose=0)
# test model
print(f"1, 2, 3 next? {model.predict([[[1],[2],[3]]])}")
print(f"2, 3, 4 next? {model.predict([[[2],[3],[4]]])}")
print(f"3, 4, 5 next? {model.predict([[[3],[4],[5]]])}")

x.shape = (3, 3, 1)
y.shape = (3, 3, 1)
Model: "functional_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (InputLayer)           [(None, 3, 1)]            0         
_________________________________________________________________
RNN0 (SimpleRNN)             (None, 3, 100)            10200     
_________________________________________________________________
RNN1 (SimpleRNN)             (None, 3, 100)            20100     
_________________________________________________________________
output (TimeDistributed)     (None, 3, 1)              101       
Total params: 30,401
Trainable params: 30,401
Non-trainable params: 0
_________________________________________________________________
1, 2, 3 next? [[[1.896312 ]
  [2.9652488]
  [3.987849 ]]]
2, 3, 4 next? [[[3.1238365]
  [4.1342974]
  [5.127207 ]]]
3, 4, 5 next? [[[3.977939 ]
  [4.947735 ]
  [5.9674087]]]


In [21]:
# SimpleRNN 대신 LSTM을 사용

import numpy as np
import tensorflow as tf
# data
xa = [[1],[2],[3]]; ya = [4]
xb = [[2],[3],[4]]; yb = [5]
xc = [[3],[4],[5]]; yc = [6]
x = np.array([xa, xb, xc])
y = np.array([ya, yb, yc])
# make a model
input_layer = tf.keras.Input(shape=(3,1), name='input')
rnn_layer = tf.keras.layers.LSTM(100, name='RNN')(input_layer)
output_layer = tf.keras.layers.Dense(1, name='output')(rnn_layer)
model = tf.keras.Model(input_layer, output_layer)
model.summary()
# compile & run
model.compile(loss='mse', optimizer='adam')
model.fit(x, y, epochs=100, batch_size=1, verbose=0)
# test model
print(f"1, 2, 3 next? {model.predict([[[1],[2],[3]]])}")
print(f"2, 3, 4 next? {model.predict([[[2],[3],[4]]])}")
print(f"3, 4, 5 next? {model.predict([[[3],[4],[5]]])}")

Model: "functional_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (InputLayer)           [(None, 3, 1)]            0         
_________________________________________________________________
RNN (LSTM)                   (None, 100)               40800     
_________________________________________________________________
output (Dense)               (None, 1)                 101       
Total params: 40,901
Trainable params: 40,901
Non-trainable params: 0
_________________________________________________________________
1, 2, 3 next? [[3.8896947]]
2, 3, 4 next? [[5.1213493]]
3, 4, 5 next? [[5.953287]]


In [ ]:
# LSTM을 이용한 주식가격 예측
# LSTM을 이용한 오존 예측
# LSTM을 이용한 월 단위 가스 사용량 예측